# -*- coding: utf-8 -*-
"""Day-09|AM_Submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkXkCbGtTyz_iphu6RnJ1J91Na1KPz5u

Day-9 | TAKE-HOME ASSIGNMENT — (05/03/2026 | AM)

Part A — Concept Application
"""

# Student Management System

# Initial student records
records = [
    ["Aman", "Math", 88],
    ["Priya", "Physics", 91],
    ["Rahul", "Math", 76],
    ["Neha", "Chemistry", 84],
    ["Arjun", "Physics", 79],
    ["Kavya", "Math", 93],
    ["Rohan", "Chemistry", 72],
    ["Simran", "Physics", 87],
    ["Aditya", "Math", 81],
    ["Meera", "Chemistry", 89]
]


def add_student(name, subject, marks):
    # Prevent duplicate name + subject
    for r in records:
        if r[0] == name and r[1] == subject:
            print("Record already exists.")
            return

    records.append([name, subject, marks])
    print("Student added successfully.")


def get_toppers(subject):
    subject_students = [r for r in records if r[1] == subject]

    if not subject_students:
        print("No records found.")
        return

    sorted_students = sorted(subject_students, key=lambda x: x[2], reverse=True)

    print("\nTop 3 Students:")
    for s in sorted_students[:3]:  # slicing
        print(s)


def class_average(subject):
    marks = [m[2] for m in records if m[1] == subject]

    if not marks:
        print("No records found.")
        return

    avg = sum(marks) / len(marks)
    print(f"Average marks in {subject}: {avg:.2f}")


def above_average_students():
    all_marks = [r[2] for r in records]

    if not all_marks:
        print("No records available.")
        return

    overall_avg = sum(all_marks) / len(all_marks)

    students = [r for r in records if r[2] > overall_avg]

    print(f"\nOverall Class Average: {overall_avg:.2f}")
    print("Students Above Average:")
    for s in students:
        print(s)


def remove_student(name):
    global records

    before_count = len(records)

    # remove using comprehension (not remove in loop)
    records = [r for r in records if r[0] != name]

    after_count = len(records)

    if before_count == after_count:
        print("Student not found.")
    else:
        print("Student records removed.")


def save_to_file():
    with open("students.txt", "w") as f:
        for r in records:
            line = f"{r[0]}, {r[1]}, {r[2]}\n"
            f.write(line)


def menu():
    while True:

        print("\n--- Student Management System ---")
        print("1 Add student")
        print("2 Show toppers")
        print("3 Show class average")
        print("4 Show above-average students")
        print("5 Remove student")
        print("6 Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            name = input("Name: ")
            subject = input("Subject: ")
            marks = int(input("Marks: "))
            add_student(name, subject, marks)

        elif choice == "2":
            subject = input("Enter subject: ")
            get_toppers(subject)

        elif choice == "3":
            subject = input("Enter subject: ")
            class_average(subject)

        elif choice == "4":
            above_average_students()

        elif choice == "5":
            name = input("Enter student name: ")
            remove_student(name)

        elif choice == "6":
            save_to_file()
            print("Data saved to students.txt")
            print("Exiting program...")
            break

        else:
            print("Invalid choice.")


# Run program
menu()

"""Part B — Stretch Problem"""

# Matrix Operations using Lists

def matrix_add(A, B):
    """Return element-wise addition of matrices A and B"""

    # Check dimension compatibility
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        print("Matrix addition not possible: dimension mismatch.")
        return None

    result = [
        [A[i][j] + B[i][j] for j in range(len(A[0]))]
        for i in range(len(A))
    ]

    return result


def matrix_transpose(matrix):
    """Return transpose of matrix"""

    # Using nested list comprehension
    return [
        [row[i] for row in matrix]
        for i in range(len(matrix[0]))
    ]

    # Alternative (Pythonic):
    # return [list(col) for col in zip(*matrix)]


def matrix_multiply(A, B):
    """Return matrix multiplication result of A and B"""

    # Check if multiplication is possible
    if len(A[0]) != len(B):
        print("Matrix multiplication not possible: dimension mismatch.")
        return None

    result = [
        [
            sum(a * b for a, b in zip(row_a, col_b))
            for col_b in zip(*B)
        ]
        for row_a in A
    ]

    return result


# ---------------------------
# Testing
# ---------------------------

if __name__ == "__main__":

    a = [[1, 2],
         [3, 4]]

    b = [[5, 6],
         [7, 8]]

    print("Matrix A:", a)
    print("Matrix B:", b)

    print("\nAddition:")
    print(matrix_add(a, b))

    print("\nTranspose of A:")
    print(matrix_transpose(a))

    print("\nMultiplication:")
    print(matrix_multiply(a, b))

    # Second test with different sizes

    c = [[1, 2, 3],
         [4, 5, 6]]

    d = [[7, 8],
         [9, 10],
         [11, 12]]

    print("\nSecond Multiplication Test:")
    print(matrix_multiply(c, d))

"""Part C — Interview Ready

Q1 — Shallow Copy vs Deep Copy

1. Shallow Copy

    A shallow copy creates a new outer container but does not copy nested objects.
    Inner objects still reference the same memory locations.

    Meaning:

          Outer list → new object

          Inner lists → same objects
"""

#Example
import copy

original = [[1, 2], [3, 4]]

shallow = copy.copy(original)

shallow[0][0] = 99

print(original)
print(shallow)

"""**Why It Fails**

Because both lists point to the same nested list.

Memory representation:

    original ---> [ refA , refB ]
    shallow  ---> [ refA , refB ]

    refA ---> [1,2]
    refB ---> [3,4]

Changing refA affects both.

2. **Deep Copy**

    A deep copy duplicates the entire structure including all nested objects.
"""

import copy

original = [[1, 2], [3, 4]]

deep = copy.deepcopy(original)

deep[0][0] = 99

print(original)
print(deep)

"""Memory representation:

    original ---> [ refA , refB ]
    deep     ---> [ refC , refD ]

    refA -> [1,2]
    refB -> [3,4]

    refC -> [1,2]
    refD -> [3,4]

All objects are independent.

**When Deep Copy Is Required**

Use deep copy when:

      

     1.  Data structures contain nested lists/dictionaries

     2. Modifying a copy must not affect the original

     3. Working with matrix data

     4. Working with config/state cloning

     5. Building algorithms that mutate structures



Typical cases:

     1. Graph algorithms

     2. Backtracking

     3. Matrix transformations

     4. Game state simulations

Q2 — List Rotation
Problem

Rotate list to the right by k positions.
"""

def rotate_list(lst, k):

    n = len(lst)

    if n == 0:
        return lst

    k = k % n   # handle k > length

    return lst[-k:] + lst[:-k]

print(rotate_list([1,2,3,4,5], 2))

"""Q3 — Debug Problem
Given Code
"""

# nums = [1, 2, 3, 4, 5, 6, 7, 8]
nums = [2,4,6,8]

for num in nums:
    if num % 2 == 0:
        nums.remove(num)

print(nums)

"""**Why the Bug Happens**

The issue is modifying a list while iterating over it.

During iteration, Python internally maintains an index pointer.

When an element is removed:

    1. The list shifts left

    2. The loop moves to the next index

    3. One element gets skipped

num = 2 → remove → list becomes [4,6,8]

    iterator moves forward

    next element checked → 6
"""

# nums = [1,2,3,4,5,6,7,8]
nums = [2,4,6,8]

nums = [n for n in nums if n % 2 != 0]

print(nums)

"""Part D — AI-Augmented Task

Prompt Used:

Write a Python function that finds all pairs in a list that sum to a target number using list comprehensions.
"""

#AI Generated Code
def find_pairs(nums, target):
    return [(a, b) for a in nums for b in nums if a + b == target]

print(find_pairs([1,2,3,4,5], 6))

print(find_pairs([1,1,1], 2))

"""4. Issues Found
  1. Duplicate Pairs

  The algorithm generates:

      (1,5) and (5,1)

   Both represent the same pair, which should not be repeated.

  2. Self Pairing Bug

    Example:

      (3,3)

   This pair appears even though the list contains only one 3.

  3. Exponential Duplicate Generation

  Example input:

      [1,1,1]

  Output:

      6 identical pairs

  Reason:

  The algorithm compares every element with every other element, including itself.

      Complexity of AI Code
      Time Complexity: O(n²)
      Space Complexity: O(n²)

  Because it checks all possible combinations.
"""

# 5. Improved Version (Remove Duplicate Pairs)

# Using index-based comprehension.

def find_pairs_unique(nums, target):

    return [
        (nums[i], nums[j])
        for i in range(len(nums))
        for j in range(i + 1, len(nums))
        if nums[i] + nums[j] == target
    ]

print(find_pairs_unique([1,2,3,4,5], 6))

print(find_pairs_unique([1,1,1], 2))

"""Best Optimized Solution (O(n))"""

def pair_sum_optimized(nums, target):

    seen = set()
    pairs = set()

    for num in nums:

        complement = target - num

        if complement in seen:
            pairs.add(tuple(sorted((num, complement))))

        seen.add(num)

    return list(pairs)

print(pair_sum_optimized([1,2,3,4,5], 6))

print(pair_sum_optimized([1,1,1], 2))

