# -*- coding: utf-8 -*-
"""frozenset_bundles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFSOGK2RGEUGX-s-ov5jX8rbPKtpWdaj

Part A — Concept Application

1️⃣ What is a frozenset?

A frozenset is an immutable version of a set in Python.
Once created, its elements cannot be added, removed, or modified.

Example:
    s = set([1,2,3])        # mutable
    f = frozenset([1,2,3])  # immutable


Difference between set and frozenset:

| Feature | set | frozenset |
|--------|-----|-----------|
| Mutable | Yes | No |
| Can add/remove items | Yes | No |
| Hashable | No | Yes |
| Can be dictionary key | No | Yes |

Because frozensets are hashable, they can be used as:
- dictionary keys
- elements inside other sets


When used in real systems:

frozensets are useful when representing fixed groups of items,
such as:

- product bundles
- permission sets
- graph edges
- cache keys
- configuration combinations

In this assignment we use frozenset to represent
product category bundles for discounts.
'''
"""

import timeit


# 2️⃣ Bundle Discount System

bundle_discounts = {
    frozenset({"Electronics", "Books"}): 10,
    frozenset({"Clothing", "Home"}): 15,
    frozenset({"Electronics", "Home"}): 12
}


# 3️⃣ Bundle Checker Function

def check_bundle_discount(cart):

    """
    cart: list of product categories
    example: ['Electronics','Books','Clothing']
    """

    cart_categories = set(cart)

    for bundle, discount in bundle_discounts.items():

        if bundle.issubset(cart_categories):
            return discount

    return 0


# Example test
cart_example = ["Electronics", "Books", "Clothing"]

print("Discount for cart:", check_bundle_discount(cart_example), "%")


# 4️⃣ Performance Benchmark

"""
We compare the time required to create a set vs a frozenset
over 100000 iterations using timeit.
"""

set_time = timeit.timeit(
    "set(['Electronics','Books','Home'])",
    number=100000
)

frozenset_time = timeit.timeit(
    "frozenset(['Electronics','Books','Home'])",
    number=100000
)

print("\nBenchmark Results")
print("Set creation time:", set_time)
print("Frozenset creation time:", frozenset_time)

"""'''
Expected Observation:

frozenset creation is slightly slower than set creation because
Python must ensure immutability.

Typical results (approx):

set creation       ≈ 0.02 sec
frozenset creation ≈ 0.03 sec

However, frozensets provide advantages when:
- used as dictionary keys
- used in caching
- used in immutable configuration structures
'''
"""

