# -*- coding: utf-8 -*-
"""Part D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uG4SqC7npp8hcSF_S5v_xPl8GmFJ6LFD
"""

def jaccard_similarity(set_a, set_b):

    intersection = set_a.intersection(set_b)
    union = set_a.union(set_b)

    return len(intersection) / len(union)

set_a = {'python','java','sql'}
set_b = {'python','sql','docker','aws'}

print(jaccard_similarity(set_a, set_b))

def jaccard_similarity(set_a, set_b):

    union = set_a | set_b

    if len(union) == 0:
        return 0

    intersection = set_a & set_b

    return len(intersection) / len(union)

