# -*- coding: utf-8 -*-
"""Day-09|PM_Submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFSOGK2RGEUGX-s-ov5jX8rbPKtpWdaj

Part A — Concept Application
"""

from collections import namedtuple

# 1️⃣ Define Named Tuple
Product = namedtuple("Product", ["id", "name", "category", "price"])


# 2️⃣ Product Catalog (15 products across 4 categories)

p1 = Product(1, "Laptop", "Electronics", 75000)
p2 = Product(2, "Smartphone", "Electronics", 45000)
p3 = Product(3, "Headphones", "Electronics", 3000)
p4 = Product(4, "Smartwatch", "Electronics", 12000)

p5 = Product(5, "T-Shirt", "Clothing", 1200)
p6 = Product(6, "Jeans", "Clothing", 2500)
p7 = Product(7, "Jacket", "Clothing", 4000)
p8 = Product(8, "Sneakers", "Clothing", 3500)

p9 = Product(9, "Clean Code", "Books", 900)
p10 = Product(10, "Python Crash Course", "Books", 1200)
p11 = Product(11, "Atomic Habits", "Books", 800)

p12 = Product(12, "Coffee Maker", "Home", 2500)
p13 = Product(13, "Blender", "Home", 2000)
p14 = Product(14, "Desk Lamp", "Home", 1500)
p15 = Product(15, "Vacuum Cleaner", "Home", 7000)

catalog = {p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15}


# 3️⃣ Customer Cart Sets

customer_1_cart = {p1, p5, p9, p12}
customer_2_cart = {p2, p5, p9, p13}
customer_3_cart = {p1, p6, p9, p14}
customer_4_cart = {p1, p7, p9, p12}
customer_5_cart = {p1, p5, p9, p15}

all_carts = [
    customer_1_cart,
    customer_2_cart,
    customer_3_cart,
    customer_4_cart,
    customer_5_cart
]


# 4️⃣ Shopping Behaviour Analysis

# (a) Bestsellers — Products in ALL carts
bestsellers = set.intersection(*all_carts)

# (b) Catalog Reach — Products in ANY cart
catalog_reach = set.union(*all_carts)

# (c) Exclusive Purchases — only customer 1 bought
exclusive_customer1 = customer_1_cart - set.union(*all_carts[1:])


# 5️⃣ Product Recommendation

def recommend_products(customer_cart, all_carts):

    other_products = set.union(*all_carts) - customer_cart

    return other_products


# 6️⃣ Category Summary

def category_summary():

    categories = {product.category for product in catalog}

    summary = {
        category: {p.name for p in catalog if p.category == category}
        for category in categories
    }

    return summary


# ----------------------------
# Demo Output
# ----------------------------

print("Bestsellers:")
for p in bestsellers:
    print(p.name)

print("\nCatalog Reach:")
for p in catalog_reach:
    print(p.name)

print("\nExclusive purchases by Customer 1:")
for p in exclusive_customer1:
    print(p.name)

print("\nRecommended for Customer 1:")
for p in recommend_products(customer_1_cart, all_carts):
    print(p.name)

print("\nCategory Summary:")
print(category_summary())

